version: '3'
services:
    client:
        build: ./client
        depends_on:
            - server
        ports:
            - "8081:80"
        restart: unless-stopped
    server:
        build: ./server
        depends_on:
            - mongo
        env_file:
            - ./server/.env
        environment:
            - SERVER_PORT=80
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
        ports:
            - "8082:80"
        restart: unless-stopped
    mongo:
        env_file:
            - ./server/.env
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mongodb_data_volume:/data/db
            - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js

volumes:
    mongodb_data_volume: